language: node_js
node_js:
  - "8"
  - "10"
before_install:
  - npm i -g npm@latest
before_script:
  - cp config.js.example config.js
script:
  - W3C_API_KEY=${W3C_API_KEY:-foo} npm run build
after_script:
  - npm run coveralls
notifications:
  email: false
  irc:
    channels:
      - "irc.w3.org#pub"
    skip_join: true
    template:
      - "%{branch} by %{author} (%{build_url}): %{message}"
